version: '3'
services:
  postgres-12-alpine:
    container_name: postgres-alpine
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sample
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=ja_JP.UTF-8
    volumes:
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"